---
driver:
  name: docker
  use_sudo: false

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true
  idempotency_test: true

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04

verifier:
  name: serverspec

suites:
  - name: python3
    driver:
      provision_command:
        - export LC_ALL=C
        - mkdir -p /run/sshd
    verifier:
      default_pattern: true
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
  - name: python2
    driver:
      provision_command:
        - export LC_ALL=C
        - mkdir -p /run/sshd
    verifier:
      default_pattern: true
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'