---
driver:
  name: docker
  use_sudo: false

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true
  idempotency_test: true

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: williamyeh/ansible:ubuntu16.04-onbuild
      platform: ubuntu

verifier:
  name: serverspec

suites:
  - name: default
    driver:
      provision_command: export LC_ALL=C
    verifier:
      default_pattern: true
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'